import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';
import { getPrisma } from '../lib/prisma.js';
import { appendEvent } from '../lib/events.js';
import { readArtifact } from '../lib/artifacts.js';
import { findFeatureById, updateFeatureStatus } from '../lib/features.js';
import { createAdoPullRequest, parseAdoRepoUrl } from '../lib/ado.js';
import type { RepoEntry } from './devJob.js';

// ── PR body helpers ───────────────────────────────────────────────────────────

const PR_BODY_BUDGET = 3900;
const TRUNCATION_MARKER = '\n\n…(truncated — see spec)';

interface PrTask {
  title: string;
  commitSha: string | null;
}

function extractSpecOverview(specMd: string, budget: number): string {
  // Take up to the end of the second paragraph (heading + first body paragraph).
  // The first \n\n separates the heading from the body; the second ends the first body para.
  const firstBreak = specMd.indexOf('\n\n');
  const secondBreak = firstBreak >= 0 ? specMd.indexOf('\n\n', firstBreak + 2) : -1;
  const overview = secondBreak > 0 ? specMd.slice(0, secondBreak) : specMd.slice(0, budget);
  return overview.slice(0, budget);
}

export function buildPrBody(
  featureSlug: string,
  featureName: string,
  repoTasks: PrTask[],
  specMd: string | null,
): string {
  const summaryBlock =
    `## ${featureName}\n` +
    `\`${featureSlug}\`\n\n` +
    `Full spec: \`features/${featureSlug}/spec.md\` in ${path.basename(process.env['ARTIFACTS_REPO_PATH'] ?? 'orrery-artifacts')}`;

  const taskLines = repoTasks
    .map((t) => `- [x] ${t.title}${t.commitSha ? ` (${t.commitSha.slice(0, 7)})` : ''}`)
    .join('\n');
  const taskBlock = `## Tasks\n${taskLines}`;

  const footerBlock = `---\n🤖 Generated by ${process.env['BOT_GIT_NAME'] ?? 'Orrery'}`;

  // Budget remaining after mandatory blocks + separators + footer.
  const fixedLen = summaryBlock.length + 2 + taskBlock.length + 2 + footerBlock.length;
  const specBudget = Math.max(0, PR_BODY_BUDGET - fixedLen - 50);
  const specOverview = specMd ? extractSpecOverview(specMd, specBudget) : '';
  const specBlock = specOverview ? `## Spec overview\n${specOverview}` : '';

  const assembled = [summaryBlock, taskBlock, specBlock, footerBlock].filter(Boolean).join('\n\n');

  if (assembled.length <= PR_BODY_BUDGET) return assembled;

  // Safety net — should not normally fire given the budget arithmetic above.
  const truncated = assembled.slice(0, PR_BODY_BUDGET - TRUNCATION_MARKER.length);
  return truncated + TRUNCATION_MARKER;
}

const MANIFEST_PATH = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../../../docs/agents/repo-manifest.yaml',
);

function getRepoEntries(manifestPath = MANIFEST_PATH): RepoEntry[] {
  const raw = fs.readFileSync(manifestPath, 'utf-8');
  const manifest = yaml.load(raw) as { repos: RepoEntry[] };
  return manifest.repos.filter((r) => r.active);
}

export async function runCreateAdoPrJob(
  featureId: string,
  _bullJobId: string,
  opts?: { manifestPath?: string },
): Promise<'completed' | 'parked'> {
  const feature = await findFeatureById(featureId);
  if (!feature) {
    console.error(JSON.stringify({ event: 'create_ado_pr_missing_feature', featureId }));
    return 'parked';
  }

  const pat = process.env['AZURE_DEVOPS_PAT'];
  if (!pat) {
    try {
      await appendEvent(getPrisma(), featureId, {
        type: 'agent.log',
        agent: 'orchestrator',
        severity: 'action',
        text: '✗ AZURE_DEVOPS_PAT env var is not set — cannot create pull requests. Set it and redispatch.',
      });
    } catch (logErr: unknown) {
      console.error(
        JSON.stringify({
          event: 'append_event_failed',
          featureId,
          error: logErr instanceof Error ? logErr.message : String(logErr),
        }),
      );
    }
    await updateFeatureStatus(featureId, 'FAILED');
    return 'parked';
  }

  // currentBranches maps repoId → exact branch name pushed to ADO by the dev agent.
  // Use this as the authoritative source for source refs — never reconstruct from slug.
  const currentBranches = feature.current_branches;

  if (Object.keys(currentBranches).length === 0) {
    try {
      await appendEvent(getPrisma(), featureId, {
        type: 'agent.log',
        agent: 'orchestrator',
        severity: 'action',
        text: '✗ currentBranches map is empty — no branches were pushed. Cannot create pull requests.',
      });
    } catch (logErr: unknown) {
      console.error(
        JSON.stringify({
          event: 'append_event_failed',
          featureId,
          error: logErr instanceof Error ? logErr.message : String(logErr),
        }),
      );
    }
    await updateFeatureStatus(featureId, 'FAILED');
    return 'parked';
  }

  // Load all completed tasks grouped by repo (for PR body task list only).
  const tasks = await getPrisma().task.findMany({
    where: { featureId, status: 'completed' },
    orderBy: { createdAt: 'asc' },
  });

  const repoEntries = getRepoEntries(opts?.manifestPath);
  const repoMap = new Map(repoEntries.map((r) => [r.id, r]));

  const specMd = readArtifact(feature.slug, 'spec.md') ?? readArtifact(feature.slug, 'spec.txt');

  // Guard against duplicate PR creation on retry: if a pr.created event already
  // exists for a repo (successful partial run before failure), skip it.
  const existingPrEvents = await getPrisma().event.findMany({
    where: { featureId, type: 'pr.created' },
  });
  const alreadyCreated = new Set(existingPrEvents.map((e) => (e.payload as { repo: string }).repo));

  // Iterate the currentBranches map — one PR per (repo, branch) pair.
  for (const [repoId, branchName] of Object.entries(currentBranches)) {
    if (alreadyCreated.has(repoId)) {
      continue;
    }

    const repoEntry = repoMap.get(repoId);
    if (!repoEntry) {
      await appendEvent(getPrisma(), featureId, {
        type: 'agent.log',
        agent: 'orchestrator',
        severity: 'action',
        text: `✗ Repo '${repoId}' not found in manifest — skipping PR creation.`,
      });
      continue;
    }

    const repoTasks = tasks.filter((t) => t.repo === repoId);

    const prTitle = `feat: ${feature.name} (${feature.slug})`;
    const body = buildPrBody(feature.slug, feature.name, repoTasks, specMd);

    let parsed: { orgUrl: string; project: string; repoId: string };
    try {
      parsed = parseAdoRepoUrl(repoEntry.url);
    } catch (err) {
      try {
        await appendEvent(getPrisma(), featureId, {
          type: 'agent.log',
          agent: 'orchestrator',
          severity: 'action',
          text: `✗ Cannot parse repo URL for ${repoId}: ${err instanceof Error ? err.message : String(err)}`,
        });
      } catch (logErr: unknown) {
        console.error(
          JSON.stringify({
            event: 'append_event_failed',
            featureId,
            error: logErr instanceof Error ? logErr.message : String(logErr),
          }),
        );
      }
      await updateFeatureStatus(featureId, 'FAILED');
      return 'parked';
    }

    try {
      const { prId, prUrl } = await createAdoPullRequest({
        ...parsed,
        pat,
        title: prTitle,
        description: body,
        sourceBranch: `refs/heads/${branchName}`,
        targetBranch: `refs/heads/${repoEntry.default_branch}`,
      });

      await appendEvent(getPrisma(), featureId, {
        type: 'pr.created',
        repo: repoId,
        pr_id: prId,
        pr_url: prUrl,
        title: prTitle,
      });

      await appendEvent(getPrisma(), featureId, {
        type: 'agent.log',
        agent: 'orchestrator',
        severity: 'ok',
        text: `✓ PR #${prId} opened for ${repoId}: ${prUrl}`,
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      try {
        await appendEvent(getPrisma(), featureId, {
          type: 'agent.log',
          agent: 'orchestrator',
          severity: 'action',
          text: `✗ PR creation failed for ${repoId}: ${msg}`,
        });
      } catch (logErr: unknown) {
        console.error(
          JSON.stringify({
            event: 'append_event_failed',
            featureId,
            error: logErr instanceof Error ? logErr.message : String(logErr),
          }),
        );
      }
      await updateFeatureStatus(featureId, 'FAILED');
      return 'parked';
    }
  }

  return 'completed';
}
